Repository YouKnowGit/DBZARA_movie_system, pull requests merged in 2021-11, with the labels that each got.

#13 Create index page layout
  .gitignore
  frontend/README.md
  frontend/node_modules/.yarn-integrity
  frontend/node_modules/@babel/runtime/helpers/asyncIterator.js
  frontend/node_modules/@babel/runtime/helpers/esm/asyncIterator.js
  frontend/node_modules/@babel/runtime/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/App.js
  frontend/src/Components/Footer.js
  frontend/src/Components/GlobalStyles.js
  frontend/src/Components/Header.js
  frontend/src/Components/MoviePoster.js
  frontend/src/Components/Router.js
  frontend/src/Routes/Event.js
  frontend/src/Routes/Home.js
  frontend/src/Routes/Movies.js
  frontend/src/Routes/Reservation.js
  frontend/src/Routes/Store.js
  frontend/yarn.lock
Labels: enhancement

#15 영화관 및 상영관 더미데이터 생성 코드 작성 및 스케쥴 더미데이터 생성 코드 작성
  backend/1347175.jpg
  backend/1566012.jpg
  backend/21127.jpg
  backend/2228586.jpg
  backend/231476.jpg
  backend/25.jpg
  backend/75913.jpg
  backend/77188.jpg
  backend/accounts/admin.py
  backend/cinema/admin.py
  backend/cinema/management/commands/__init__.py
  backend/cinema/management/commands/create_cinema.py
  backend/cinema/management/commands/create_schedule.py
  backend/cinema/management/commands/data.json
  backend/cinema/models/base.py
  backend/exception/__init__.py
  backend/exception/movie_exception.py
  backend/functions/collect_cinema_data.py
  backend/functions/collect_movie_data.py
  backend/movie/management/commands/create_movie.py
  backend/movie_system/secret_settings.py
  backend/movie_system/settings.py
  backend/requirements.txt
Labels: enhancement, help wanted

#17 Refactoring python files & create index page
  .gitignore
  backend/cinema/management/commands/create_cinema.py
  backend/cinema/management/commands/create_schedule.py
  backend/functions/collect_movie_data.py
  backend/movie/management/commands/create_movie.py
  backend/movie_system/settings.py
  backend/movie_system/storages.py
  backend/movie_system/templates/_base.html
  backend/movie_system/templates/_footer.html
  backend/movie_system/templates/_sidebar.html
  backend/movie_system/templates/_topbar.html
  backend/movie_system/templates/index.html
  backend/movie_system/urls.py
  backend/requirements.txt
Labels: enhancement, good first issue

#18 fix accounts model - Department
  backend/accounts/admin.py
  backend/accounts/models/employee.py
  backend/accounts/models/user.py
  backend/accounts/static/icon/naver.ico
  backend/accounts/templates/accounts/login.html
  backend/accounts/urls.py
  backend/accounts/views.py
  backend/accounts/views/__init__.py
  backend/accounts/views/google_login.py
  backend/accounts/views/kakao_login.py
  backend/accounts/views/naver_login.py
  backend/movie_system/settings.py
  backend/movie_system/templates/_sidebar.html
  backend/movie_system/templates/_topbar.html
  backend/movie_system/urls.py
  backend/requirements.txt
Labels: enhancement, fix

#19 ADD social login & jwt validation
  backend/accounts/admin.py
  backend/accounts/models/employee.py
  backend/accounts/models/user.py
  backend/accounts/static/icon/naver.ico
  backend/accounts/templates/accounts/login.html
  backend/accounts/urls.py
  backend/accounts/views.py
  backend/accounts/views/__init__.py
  backend/accounts/views/google_login.py
  backend/accounts/views/kakao_login.py
  backend/accounts/views/naver_login.py
  backend/movie_system/settings.py
  backend/movie_system/templates/_sidebar.html
  backend/movie_system/templates/_topbar.html
  backend/movie_system/urls.py
  backend/requirements.txt
Labels: enhancement

#20 Add CORS ORIGIN
  backend/movie_system/settings.py
  backend/requirements.txt
Labels: enhancement

#29 Create Movie Views
  backend/accounts/management/commands/create_employees.py
  backend/functions/collect_movie_data.py
  backend/item/models/base.py
  backend/movie/models.py
  backend/movie/static/css/model-card.css
  backend/movie/static/css/movie-card.css
  backend/movie/static/img/no-photo-available.jpeg
  backend/movie/templates/movie/_card.html
  backend/movie/templates/movie/_form.html
  backend/movie/templates/movie/movie_card.html
  backend/movie/templates/movie/movie_list.html
  backend/movie/templates/movie/person_list.html
  backend/movie/urls.py
  backend/movie/views.py
  backend/movie_system/settings.py
  backend/movie_system/templates/_pagination.html
  backend/movie_system/templates/_search_bar.html
  backend/movie_system/templates/_sidebar.html
  backend/movie_system/urls.py
  backend/requirements.txt
Labels: enhancement

#35 Create Order & Reservation Dummy Data functions
  backend/accounts/admin.py
  backend/accounts/management/commands/create_user.py
  backend/accounts/models/user.py
  backend/cinema/admin.py
  backend/cinema/management/commands/create_cinema.py
  backend/cinema/management/commands/create_schedule.py
  backend/cinema/models/base.py
  backend/cinema/static/css/list-section.css
  backend/cinema/static/css/scheduler.css
  backend/cinema/templates/cinema/cinema_list.html
  backend/cinema/templates/cinema/scheduler.html
  backend/cinema/urls.py
  backend/cinema/views/__init__.py
  backend/cinema/views/list.py
  backend/collect_data.sh
  backend/exception/cinema_exception.py
  backend/exception/movie_exception.py
  backend/functions/collect_movie_data.py
  backend/functions/crawling_office_item.py
  backend/item/admin.py
  backend/item/models/base.py
  backend/item/models/event.py
  backend/movie/admin.py
  backend/movie/management/commands/create_movie.py
  backend/movie/models.py
  backend/movie/serializers.py
  backend/movie/serializers/__init__.py
  backend/movie/serializers/base.py
  backend/movie/serializers/movie.py
  backend/movie/static/css/movie-card.css
  backend/movie/static/css/profile-card.css
  backend/movie/templates/movie/_card.html
  backend/movie/templates/movie/distributor_list.html
  backend/movie/templates/movie/genre_list.html
  backend/movie/templates/movie/movie_card.html
  backend/movie/templates/movie/movie_detail.html
  backend/movie/templates/movie/movie_list.html
  backend/movie/templates/movie/person_detail.html
  backend/movie/templates/movie/person_list.html
  backend/movie/templatetags/__init__.py
  backend/movie/templatetags/movie_tags.py
  backend/movie/urls.py
  backend/movie/views/__init__.py
  backend/movie/views/api.py
  backend/movie/views/detail.py
  backend/movie/views/list.py
  backend/movie_system/settings.py
  backend/movie_system/templates/_base.html
  backend/movie_system/templates/_sidebar.html
  backend/movie_system/templates/_table.html
  backend/movie_system/urls.py
  backend/remove_migrations.sh
  backend/requirements.txt
Labels: enhancement
